### ISSUE TITLE
نکات  UI

### ISSUE THREAD

**Issue by rezakho** [caspeen/jazbeniru#7]
برای آقا مهرداد

- عناصر فرم با این ساختار نوشت بشن
```html
<div class="form-row">
    <label class="control-label" for="id">Id</label>
    <input type="text" class="form-control" id="id">
    <div class="error-message"></div>
</div>
```
- برای عناصر فرم، الرت ها و ... از کلاس های بوت استرپ استفاده بشه
- کلاس های زیر برای فرم ها به علاوه کلاس های بوت استرپ به پروژه اضافه بشه
```css
.form-row{
	margin: 0 0 30px 0;
}

.form-row:nth-last-of-type(1){
	margin-bottom: 0;
}

.form-row label{
	display: block;
	direction: rtl;
	text-align: right;
	margin: 0 0 5px 0;
}

.form-row .error-message{
	color: #b24626;
	direction: rtl;
	text-align: right;
	display: none;
}

.form-row.has-error .error-message{
	display: block;
}

.form-row.has-error input{
	border-color: #b24626;
}
```
